"""empty message

Revision ID: 0600d4e565dd
Revises: 9425dc50235a
Create Date: 2016-05-03 07:52:47.489116

"""

# revision identifiers, used by Alembic.
revision = '0600d4e565dd'
down_revision = '9425dc50235a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship',
    sa.Column('person1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('person2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['person1'], [u'person.id'], name=u'relationship_person1_fkey'),
    sa.ForeignKeyConstraint(['person2'], [u'person.id'], name=u'relationship_person2_fkey'),
    sa.PrimaryKeyConstraint('person1', 'person2', name=u'relationship_pkey')
    )
    ### end Alembic commands ###
