"""empty message

Revision ID: 06cefb4b4b1d
Revises: 92f18c9d1403
Create Date: 2016-05-06 08:49:49.210644

"""

# revision identifiers, used by Alembic.
revision = '06cefb4b4b1d'
down_revision = '92f18c9d1403'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('followee_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('followee_id', 'follower_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship')
    ### end Alembic commands ###
