"""empty message

Revision ID: 06fbf1a331b7
Revises: 64b3fecc7e49
Create Date: 2016-05-13 08:31:47.403303

"""

# revision identifiers, used by Alembic.
revision = '06fbf1a331b7'
down_revision = '64b3fecc7e49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('book_isbn', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['book_isbn'], ['book.isbn'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'book_isbn')
    )
    op.drop_constraint(u'book_genre_id_fkey', 'book', type_='foreignkey')
    op.drop_constraint(u'book_author_id_fkey', 'book', type_='foreignkey')
    op.drop_column(u'book', 'author_id')
    op.drop_column(u'book', 'genre_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'book', sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'book', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'book_author_id_fkey', 'book', 'author', ['author_id'], ['id'])
    op.create_foreign_key(u'book_genre_id_fkey', 'book', 'genre', ['genre_id'], ['id'])
    op.drop_table('book_genre')
    ### end Alembic commands ###
