"""empty message

Revision ID: 119c2d9f303d
Revises: 8f877284daae
Create Date: 2016-04-30 08:33:50.425832

"""

# revision identifiers, used by Alembic.
revision = '119c2d9f303d'
down_revision = '8f877284daae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'img')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('img', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    ### end Alembic commands ###
