"""empty message

Revision ID: 1dd7162f4c1d
Revises: aa797bd4dda2
Create Date: 2016-04-28 08:43:30.384437

"""

# revision identifiers, used by Alembic.
revision = '1dd7162f4c1d'
down_revision = 'aa797bd4dda2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('person', sa.Column('img', sa.String(length=45), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'img')
    op.drop_column('person', 'age')
    ### end Alembic commands ###
