"""empty message

Revision ID: 20d8f9476f44
Revises: 37465dd4f6bd
Create Date: 2016-05-06 22:34:46.772871

"""

# revision identifiers, used by Alembic.
revision = '20d8f9476f44'
down_revision = '37465dd4f6bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('first_name', sa.String(length=45), nullable=True))
    op.add_column('student', sa.Column('last_name', sa.String(length=45), nullable=True))
    op.drop_column('student', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('name', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.drop_column('student', 'last_name')
    op.drop_column('student', 'first_name')
    ### end Alembic commands ###
