"""empty message

Revision ID: 22448c879de8
Revises: 9bdcbd47de38
Create Date: 2016-05-12 19:19:03.397447

"""

# revision identifiers, used by Alembic.
revision = '22448c879de8'
down_revision = '9bdcbd47de38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('page_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'page_count')
    ### end Alembic commands ###
