"""empty message

Revision ID: 2e8793b6a293
Revises: 88fe54be11e0
Create Date: 2016-04-28 08:35:37.006012

"""

# revision identifiers, used by Alembic.
revision = '2e8793b6a293'
down_revision = '88fe54be11e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library_copy', sa.Column('library_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'library_copy_libary_id_fkey', 'library_copy', type_='foreignkey')
    op.create_foreign_key(None, 'library_copy', 'library', ['library_id'], ['id'])
    op.drop_column('library_copy', 'libary_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library_copy', sa.Column('libary_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'library_copy', type_='foreignkey')
    op.create_foreign_key(u'library_copy_libary_id_fkey', 'library_copy', 'library', ['libary_id'], ['id'])
    op.drop_column('library_copy', 'library_id')
    ### end Alembic commands ###
