"""empty message

Revision ID: 2f70719fc690
Revises: d503505a486d
Create Date: 2016-04-28 08:27:28.438875

"""

# revision identifiers, used by Alembic.
revision = '2f70719fc690'
down_revision = 'd503505a486d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'synopsis')
    op.drop_column('book', 'img')
    op.drop_column('book', 'title')
    op.drop_column('library', 'name')
    op.drop_column('library', 'address')
    op.drop_column('review', 'description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('description', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('library', sa.Column('address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('library', sa.Column('name', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('book', sa.Column('title', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('book', sa.Column('img', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('book', sa.Column('synopsis', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    ### end Alembic commands ###
