"""empty message

Revision ID: 36e0e7b5e6d1
Revises: 5beaa7a50cf5
Create Date: 2016-05-11 11:03:31.469287

"""

# revision identifiers, used by Alembic.
revision = '36e0e7b5e6d1'
down_revision = '5beaa7a50cf5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('genre', sa.String(length=45), nullable=True))
    op.add_column('book', sa.Column('publication_date', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'publication_date')
    op.drop_column('book', 'genre')
    ### end Alembic commands ###
