"""empty message

Revision ID: 37465dd4f6bd
Revises: 06cefb4b4b1d
Create Date: 2016-05-06 22:05:01.258579

"""

# revision identifiers, used by Alembic.
revision = '37465dd4f6bd'
down_revision = '06cefb4b4b1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('date_checked_out', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('book_isbn', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_isbn'], ['book.isbn'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followee_follower',
    sa.Column('followee_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('followee_id', 'follower_id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_turned_in', sa.Date(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('book_isbn', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['book_isbn'], ['book.isbn'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('library_copy')
    op.drop_table('library')
    op.drop_table('friendship')
    # op.drop_table('person')
    op.add_column('review', sa.Column('student_id', sa.Integer(), nullable=True))
    # op.drop_constraint(u'review_person_id_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'student', ['student_id'], ['id'])
    op.drop_column('review', 'person_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key(u'review_person_id_fkey', 'review', 'person', ['person_id'], ['id'])
    op.drop_column('review', 'student_id')
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('person_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('img', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'person_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('friendship',
    sa.Column('followee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], [u'person.id'], name=u'friendship_followee_id_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], [u'person.id'], name=u'friendship_follower_id_fkey'),
    sa.PrimaryKeyConstraint('followee_id', 'follower_id', name=u'friendship_pkey')
    )
    op.create_table('library',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('library_id_seq'::regclass)"), nullable=False),
    sa.Column('city', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('zip', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('logo', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'library_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('library_copy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('date_checked_out', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('book_isbn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('library_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_isbn'], [u'book.isbn'], name=u'library_copy_book_isbn_fkey'),
    sa.ForeignKeyConstraint(['library_id'], [u'library.id'], name=u'library_copy_library_id_fkey'),
    sa.ForeignKeyConstraint(['person_id'], [u'person.id'], name=u'library_copy_person_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'library_copy_pkey')
    )
    op.drop_table('history')
    op.drop_table('followee_follower')
    op.drop_table('copy')
    op.drop_table('student')
    ### end Alembic commands ###
