"""empty message

Revision ID: 51524b8a50ab
Revises: 22448c879de8
Create Date: 2016-05-13 07:50:17.336223

"""

# revision identifiers, used by Alembic.
revision = '51524b8a50ab'
down_revision = '22448c879de8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'author',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('book', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('return', 'date_returned',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('review', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('review', 'description',
               existing_type=sa.VARCHAR(length=3000),
               nullable=False)
    op.alter_column('review', 'isbn',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('review', 'rating',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('review', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student', 'first_name',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('student', 'last_name',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'last_name',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('student', 'first_name',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('review', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review', 'rating',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('review', 'isbn',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('review', 'description',
               existing_type=sa.VARCHAR(length=3000),
               nullable=True)
    op.alter_column('review', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('return', 'date_returned',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('book', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('book', 'author',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    ### end Alembic commands ###
