"""empty message

Revision ID: 522700caea10
Revises: 04100625f92a
Create Date: 2016-04-28 09:13:07.693199

"""

# revision identifiers, used by Alembic.
revision = '522700caea10'
down_revision = '04100625f92a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'library_copy_library_id_fkey', 'library_copy', type_='foreignkey')
    op.drop_column('library_copy', 'library_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library_copy', sa.Column('library_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'library_copy_library_id_fkey', 'library_copy', 'library', ['library_id'], ['id'])
    ### end Alembic commands ###
