"""empty message

Revision ID: 5beaa7a50cf5
Revises: 7794a4a576b6
Create Date: 2016-05-08 13:13:54.533112

"""

# revision identifiers, used by Alembic.
revision = '5beaa7a50cf5'
down_revision = '7794a4a576b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=45), nullable=True),
    sa.Column('last_name', sa.String(length=45), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher')
    ### end Alembic commands ###
