"""empty message

Revision ID: 64b3fecc7e49
Revises: 51524b8a50ab
Create Date: 2016-05-13 08:25:01.926003

"""

# revision identifiers, used by Alembic.
revision = '64b3fecc7e49'
down_revision = '51524b8a50ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_author',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('book_isbn', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['book_isbn'], ['book.isbn'], ),
    sa.PrimaryKeyConstraint('author_id', 'book_isbn')
    )
    op.add_column(u'book', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column(u'book', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'author', ['author_id'], ['id'])
    op.create_foreign_key(None, 'book', 'genre', ['genre_id'], ['id'])
    op.drop_column(u'book', 'genre')
    op.drop_column(u'book', 'author')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'book', sa.Column('author', sa.VARCHAR(length=45), autoincrement=False, nullable=False))
    op.add_column(u'book', sa.Column('genre', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column(u'book', 'genre_id')
    op.drop_column(u'book', 'author_id')
    op.drop_table('book_author')
    op.drop_table('genre')
    op.drop_table('author')
    ### end Alembic commands ###
