"""empty message

Revision ID: 7794a4a576b6
Revises: e447cc3bc006
Create Date: 2016-05-07 22:43:48.553219

"""

# revision identifiers, used by Alembic.
revision = '7794a4a576b6'
down_revision = 'e447cc3bc006'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_search_vector', table_name='book')
    op.drop_column('book', 'search_vector')
    op.drop_index('ix_student_search_vector', table_name='student')
    op.drop_column('student', 'search_vector')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('ix_student_search_vector', 'student', ['search_vector'], unique=False)
    op.add_column('book', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('ix_book_search_vector', 'book', ['search_vector'], unique=False)
    ### end Alembic commands ###
