"""empty message

Revision ID: 78361309c2b1
Revises: 36e0e7b5e6d1
Create Date: 2016-05-11 22:20:17.192340

"""

# revision identifiers, used by Alembic.
revision = '78361309c2b1'
down_revision = '36e0e7b5e6d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_student',
    sa.Column('book_isbn', sa.String(length=45), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date_checked_out', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['book_isbn'], ['book.isbn'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('book_isbn', 'student_id')
    )
    op.drop_table('teacher')
    op.drop_table('copy')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('date_checked_out', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('book_isbn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_isbn'], [u'book.isbn'], name=u'copy_book_isbn_fkey'),
    sa.ForeignKeyConstraint(['student_id'], [u'student.id'], name=u'copy_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'copy_pkey')
    )
    op.create_table('teacher',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('img', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'teacher_pkey')
    )
    op.drop_table('book_student')
    ### end Alembic commands ###
