"""empty message

Revision ID: 88fe54be11e0
Revises: 2f70719fc690
Create Date: 2016-04-28 08:27:42.075749

"""

# revision identifiers, used by Alembic.
revision = '88fe54be11e0'
down_revision = '2f70719fc690'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('img', sa.String(length=256), nullable=True))
    op.add_column('book', sa.Column('synopsis', sa.String(length=3000), nullable=True))
    op.add_column('book', sa.Column('title', sa.String(length=256), nullable=True))
    op.add_column('library', sa.Column('address', sa.String(length=256), nullable=True))
    op.add_column('library', sa.Column('name', sa.String(length=256), nullable=True))
    op.add_column('review', sa.Column('description', sa.String(length=3000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'description')
    op.drop_column('library', 'name')
    op.drop_column('library', 'address')
    op.drop_column('book', 'title')
    op.drop_column('book', 'synopsis')
    op.drop_column('book', 'img')
    ### end Alembic commands ###
