"""empty message

Revision ID: 8f877284daae
Revises: 0b49e4b745a5
Create Date: 2016-04-30 08:25:24.294664

"""

# revision identifiers, used by Alembic.
revision = '8f877284daae'
down_revision = '0b49e4b745a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('rating', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'rating')
    ### end Alembic commands ###
