"""empty message

Revision ID: 92f18c9d1403
Revises: ffc3311e13cd
Create Date: 2016-05-06 08:49:40.124462

"""

# revision identifiers, used by Alembic.
revision = '92f18c9d1403'
down_revision = 'ffc3311e13cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('person1_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('person2_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['person1_id'], [u'person.id'], name=u'friendship_person1_id_fkey'),
    sa.ForeignKeyConstraint(['person2_id'], [u'person.id'], name=u'friendship_person2_id_fkey'),
    sa.PrimaryKeyConstraint('person1_id', 'person2_id', name=u'friendship_pkey')
    )
    ### end Alembic commands ###
