"""empty message

Revision ID: 9425dc50235a
Revises: 97c9887ebbe5
Create Date: 2016-05-02 13:51:57.519599

"""

# revision identifiers, used by Alembic.
revision = '9425dc50235a'
down_revision = '97c9887ebbe5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library_copy', sa.Column('due_date', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library_copy', 'due_date')
    ### end Alembic commands ###
