"""empty message

Revision ID: 94aa7f1565fd
Revises: a729bd43c472
Create Date: 2016-05-11 22:26:11.622899

"""

# revision identifiers, used by Alembic.
revision = '94aa7f1565fd'
down_revision = 'a729bd43c472'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return', sa.Column('id', sa.INTEGER(), nullable=False))
    ### end Alembic commands ###
