"""empty message

Revision ID: 97c9887ebbe5
Revises: bb23c47d31d2
Create Date: 2016-05-02 13:43:11.510730

"""

# revision identifiers, used by Alembic.
revision = '97c9887ebbe5'
down_revision = 'bb23c47d31d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'img')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('img', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    ### end Alembic commands ###
