"""empty message

Revision ID: 9bdcbd47de38
Revises: 00eb94d908ee
Create Date: 2016-05-11 22:47:19.274830

"""

# revision identifiers, used by Alembic.
revision = '9bdcbd47de38'
down_revision = '00eb94d908ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow', sa.Column('isbn', sa.String(length=45), nullable=False))
    op.drop_constraint(u'borrow_book_isbn_fkey', 'borrow', type_='foreignkey')
    op.create_foreign_key(None, 'borrow', 'book', ['isbn'], ['isbn'])
    op.drop_column('borrow', 'book_isbn')
    op.add_column('return', sa.Column('isbn', sa.String(length=45), nullable=False))
    op.drop_constraint(u'return_book_isbn_fkey', 'return', type_='foreignkey')
    op.create_foreign_key(None, 'return', 'book', ['isbn'], ['isbn'])
    op.drop_column('return', 'book_isbn')
    op.add_column('review', sa.Column('isbn', sa.String(), nullable=True))
    op.drop_constraint(u'review_book_isbn_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'book', ['isbn'], ['isbn'])
    op.drop_column('review', 'book_isbn')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('book_isbn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key(u'review_book_isbn_fkey', 'review', 'book', ['book_isbn'], ['isbn'])
    op.drop_column('review', 'isbn')
    op.add_column('return', sa.Column('book_isbn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'return', type_='foreignkey')
    op.create_foreign_key(u'return_book_isbn_fkey', 'return', 'book', ['book_isbn'], ['isbn'])
    op.drop_column('return', 'isbn')
    op.add_column('borrow', sa.Column('book_isbn', sa.VARCHAR(length=45), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'borrow', type_='foreignkey')
    op.create_foreign_key(u'borrow_book_isbn_fkey', 'borrow', 'book', ['book_isbn'], ['isbn'])
    op.drop_column('borrow', 'isbn')
    ### end Alembic commands ###
