"""empty message

Revision ID: aa797bd4dda2
Revises: 2e8793b6a293
Create Date: 2016-04-28 08:43:22.867734

"""

# revision identifiers, used by Alembic.
revision = 'aa797bd4dda2'
down_revision = '2e8793b6a293'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'age')
    op.drop_column('person', 'img')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('img', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('person', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
