"""empty message

Revision ID: b4996d225208
Revises: None
Create Date: 2016-04-26 09:48:10.973168

"""

# revision identifiers, used by Alembic.
revision = 'b4996d225208'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=45), nullable=True),
    sa.Column('author', sa.String(length=45), nullable=True),
    sa.Column('synopsis', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('isbn')
    )
    op.create_table('library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('address', sa.String(length=45), nullable=True),
    sa.Column('city', sa.String(length=45), nullable=True),
    sa.Column('state', sa.String(length=45), nullable=True),
    sa.Column('zip', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship',
    sa.Column('user1', sa.Integer(), nullable=False),
    sa.Column('user2', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('user1', 'user2')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('username', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=45), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_copy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('date_checked_out', sa.Date(), nullable=True),
    sa.Column('book_isbn', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('libary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_isbn'], ['book.isbn'], ),
    sa.ForeignKeyConstraint(['libary_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_isbn', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_isbn'], ['book.isbn'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('library_copy')
    op.drop_table('user')
    op.drop_table('relationship')
    op.drop_table('library')
    op.drop_table('book')
    ### end Alembic commands ###
