"""empty message

Revision ID: b8e1eeac3082
Revises: 1dd7162f4c1d
Create Date: 2016-04-28 08:44:31.225157

"""

# revision identifiers, used by Alembic.
revision = 'b8e1eeac3082'
down_revision = '1dd7162f4c1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'age')
    op.drop_column('person', 'img')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('img', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('person', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
