"""empty message

Revision ID: bb23c47d31d2
Revises: 50d734f7cb1f
Create Date: 2016-05-02 13:39:32.992776

"""

# revision identifiers, used by Alembic.
revision = 'bb23c47d31d2'
down_revision = '50d734f7cb1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('img', sa.String(length=256), nullable=True))
    op.add_column('library', sa.Column('logo', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'logo')
    op.drop_column('library', 'img')
    ### end Alembic commands ###
