"""empty message

Revision ID: bbecce189ed8
Revises: fbaf54174a98
Create Date: 2016-04-28 09:02:03.925110

"""

# revision identifiers, used by Alembic.
revision = 'bbecce189ed8'
down_revision = 'fbaf54174a98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship')
    print 'test'
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    print 'test'
    ### end Alembic commands ###
