"""empty message

Revision ID: c8e52abbc4a6
Revises: 06fbf1a331b7
Create Date: 2016-05-13 08:45:57.170619

"""

# revision identifiers, used by Alembic.
revision = 'c8e52abbc4a6'
down_revision = '06fbf1a331b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('isbn', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('synopsis', sa.String(length=3000), nullable=True),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('isbn')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_author',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('book_isbn', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['book_isbn'], ['book.isbn'], ),
    sa.PrimaryKeyConstraint('author_id', 'book_isbn')
    )
    op.create_table('book_genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('book_isbn', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['book_isbn'], ['book.isbn'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'book_isbn')
    )
    op.create_table('borrow',
    sa.Column('isbn', sa.String(length=256), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date_checked_out', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['book.isbn'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('isbn', 'student_id')
    )
    op.create_table('followee_follower',
    sa.Column('followee_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('followee_id', 'follower_id')
    )
    op.create_table('return',
    sa.Column('isbn', sa.String(length=256), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date_returned', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['isbn'], ['book.isbn'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('isbn', 'student_id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=3000), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['isbn'], ['book.isbn'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('return')
    op.drop_table('followee_follower')
    op.drop_table('borrow')
    op.drop_table('book_genre')
    op.drop_table('book_author')
    op.drop_table('student')
    op.drop_table('genre')
    op.drop_table('book')
    op.drop_table('author')
    ### end Alembic commands ###
