"""empty message

Revision ID: de35da053f98
Revises: 20d8f9476f44
Create Date: 2016-05-07 21:49:58.363871

"""

# revision identifiers, used by Alembic.
revision = 'de35da053f98'
down_revision = '20d8f9476f44'

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types import TSVectorType
sa.orm.configure_mappers()


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('search_vector', TSVectorType(), nullable=True))
    op.add_column('student', sa.Column('search_vector', TSVectorType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'search_vector')
    op.drop_column('book', 'search_vector')
    ### end Alembic commands ###
