"""empty message

Revision ID: e3166a77b70e
Revises: 0600d4e565dd
Create Date: 2016-05-03 07:53:59.246597

"""

# revision identifiers, used by Alembic.
revision = 'e3166a77b70e'
down_revision = '0600d4e565dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('person1_id', sa.Integer(), nullable=False),
    sa.Column('person2_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['person1_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['person2_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('person1_id', 'person2_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship')
    ### end Alembic commands ###
