"""empty message

Revision ID: e447cc3bc006
Revises: de35da053f98
Create Date: 2016-05-07 22:36:21.500843

"""

# revision identifiers, used by Alembic.
revision = 'e447cc3bc006'
down_revision = 'de35da053f98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_book_search_vector', 'book', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_student_search_vector', 'student', ['search_vector'], unique=False, postgresql_using='gin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_search_vector', table_name='student')
    op.drop_index('ix_book_search_vector', table_name='book')
    ### end Alembic commands ###
