"""empty message

Revision ID: fbaf54174a98
Revises: b8e1eeac3082
Create Date: 2016-04-28 08:46:47.025641

"""

# revision identifiers, used by Alembic.
revision = 'fbaf54174a98'
down_revision = 'b8e1eeac3082'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('person', sa.Column('img', sa.String(length=45), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'img')
    op.drop_column('person', 'age')
    ### end Alembic commands ###
