"""empty message

Revision ID: ffc3311e13cd
Revises: e3166a77b70e
Create Date: 2016-05-06 08:47:27.315949

"""

# revision identifiers, used by Alembic.
revision = 'ffc3311e13cd'
down_revision = 'e3166a77b70e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    print("test")
    # op.add_column('friendship', sa.Column('followee_id', sa.Integer(), nullable=False))
    # op.add_column('friendship', sa.Column('follower_id', sa.Integer(), nullable=False))
    # op.drop_constraint(u'friendship_person1_id_fkey', 'friendship', type_='foreignkey')
    # op.drop_constraint(u'friendship_person2_id_fkey', 'friendship', type_='foreignkey')
    # op.create_foreign_key(None, 'friendship', 'person', ['followee_id'], ['id'])
    # op.create_foreign_key(None, 'friendship', 'person', ['follower_id'], ['id'])
    # op.drop_column('friendship', 'person2_id')
    # op.drop_column('friendship', 'person1_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    print("test")
    # op.add_column('friendship', sa.Column('person1_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # op.add_column('friendship', sa.Column('person2_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # op.drop_constraint(None, 'friendship', type_='foreignkey')
    # op.drop_constraint(None, 'friendship', type_='foreignkey')
    # op.create_foreign_key(u'friendship_person2_id_fkey', 'friendship', 'person', ['person2_id'], ['id'])
    # op.create_foreign_key(u'friendship_person1_id_fkey', 'friendship', 'person', ['person1_id'], ['id'])
    # op.drop_column('friendship', 'follower_id')
    # op.drop_column('friendship', 'followee_id')
    ### end Alembic commands ###
